### ISSUE TITLE
[FE] 웹소켓 연결 및 채팅방 구독 로직 리팩터링

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#112]
### 🔨 Describe

채팅 서버 api 통신 버그 수정
로그인할 때 소켓 연결, 서버 생성 or 접속 시에 해당 서버 구독
다른 서버로 이동할 때 구독 해제 

### ✅ Tasks

- [x] 채팅 서버 api 통신 버그 수정
- [x] 로그인할 때 소켓 연결, 서버 생성 or 접속 시에 해당 서버 구독
- [x] 다른 서버로 이동하면 (serverId 바뀔 때) 구독 해제
