### ISSUE TITLE
[FE] 친구 기능 구현 

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#115]
### 📄 Describe

대기 중인 친구 목록
친구 목록 (온 & 오프라인) 
친구 추가, 삭제 및 거절, 요청 수락

### ✅ Tasks

- [x] 대기 중인 친구 목록
- [x] 친구 목록 (온 & 오프라인) 
- [x] 친구 추가
- [x] 친구 삭제 및 거절
- [x] 친구 요청 수락

### 🙋🏻 More
DM, 알림과 연동된 서비스 입니다. 추가적인 검토가 필요합니다.
