### ISSUE TITLE
[BE] 유저 서비스 프로젝트 초기 설정 및 기능 구현

### ISSUE THREAD

**Issue by ryudain05** [hobbytrip/hobbytrip#22]
### 📄 Describe

- 프로젝트 구조 Init
- 각종 환경설정(Config)
- 각종 예외처리(Exception)
- 각 도메인 엔티티 생성
- 시큐리티 설정
- JWT (로그인 시 토큰 발급, 토큰 재발급)
- 로그인
- 회원가입
- 로그아웃
- 회원탈퇴

### ✅ Tasks

- [x] 공통 예외를 위한 GlobalException 구현
- [x] Security 설정
- [x] User 관련 Reqeust, Response Dto 설정
- [x] Token Dto, Token Request Dto 설정
- [x] Token Util 구현
- [x] Token을 로그인/회원가입/로그아웃/로그인 확인 유무 AuthService 구현
- [x] 회원 탈퇴 기능 
- [x] refresh token -> redis

### 🙋🏻 More

아직 refresh token이 mysql에 저장됩니다 !

### 토큰

token
{
  "email": "email",
  "auth": "ROLE_USER",
  "sub": "userid",
  "iat": 1712663559,
  "exp": 1712749959
}
