### ISSUE TITLE
[FE] 로그인, 회원가입 기능 구현

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#24]
### 📄 Describe

- 시작화면 3초 유지 → 로그인 페이지로 navigate
- zustand를 사용하여 전역적으로 로그인 상태 관리
- 토큰을 사용한 유저 인증

### ✅ Tasks

- [x] 시작화면 구현
- [x] 로그인 기능 구현
- [x] 회원가입 기능 구현
- [x] JWT Token 사용한 유저 인증

### 🙋🏻 More

**Comment by yeahzee0421** [comment]
json-server 추가

**Comment by yeahzee0421** [comment]
참고한 자료: 🍪 프론트에서 안전하게 로그인 처리하기 (ft. React) 
[https://velog.io/@yaytomato/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%90%EC%84%9C-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0](url)
