### ISSUE TITLE
[BE] 카테고리 CUD, DM 프로필 이미지, 채널 CUD, 카프카 설정

### ISSUE THREAD

**Issue by HanYoonSoo** [hobbytrip/hobbytrip#32]
## 작업 대상
- DM 프로필 이미지 기능 추가
- 카테고리 Create, Update, Delete 구현
- 채널 Create, Update, Delete 구현
- 카프카 도커 설정 및 환경설정
- 기타 코드 리팩토링

### ✅ Tasks

- [x] DM 프로필 Update, Delete 관련 Dto, Service, Controller 구현
- [x] 카테고리 CUD 관련 Dto, Service, Controller 구현
- [x] 채널 CUD 관련 Dto, Service, Controller 구현
- [x] 카프카 관련 도커 설정  
- [x] 카프카 관련 Configuration 설정
- [x] 카프카 관련 yml 수정

### 🙋🏻 More

- 카프카 설정은 좀 더 고민한 후 마무리하겠습니다.
