### ISSUE TITLE
[FE] 커뮤니티 서버 생성 기능 구현

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#37]
### 🤔 Describe
유저 커뮤니티 회원가입
서버 생성 후 서버 정보 조회

### ✅ Tasks
- [x] 유저 커뮤니티 회원가입
- [x] 서버 생성 기능 구현
- [x] 서버 id, 채널 id 라우팅

### 🙋🏻 More
