### ISSUE TITLE
[BE] 채팅 서비스 코드 리팩터링

### ISSUE THREAD

**Issue by acs0209** [hobbytrip/hobbytrip#40]
### 🔨 Describe

1. 추후 현재 서비스 로직이 다른 서비스 로직으로 바뀌는 것을 고려해 유연하게 변경이 용이한 코드를 만들기 위해 컨트롤러가 인터페이스를 의존하도록 리팩터링을 했습니다.
2. 하나의 클래스에서 query, command를 담당하다 보니 하나의 클래스가 많은 역할을 담당한다고 생각해 클래스의 역할을 분리하기 위해 query와 command로 분리했습니다.
3. 빌더 패턴과 정적 팩토리 메서드 둘 중 하나만 사용해도 충분하다고 생각해 둘을 혼합한 코드에서 빌더 패턴을 제거하고 정적 팩토리 메서드만 사용하도록 리팩터링 했습니다.

### ✅ Tasks

- [x] 서비스 로직에 인터페이스를 추가해서 컨트롤러가 구현체가 아닌 인터페이스에 의존하게 했습니다.
- [x] 컨트롤러, 서비스를 query, command로 분리했습니다.
- [x] DTO에서 정적 팩토리 메서드, 빌더 패턴을 혼합했는데 빌더 패턴을 제거하고 정적 팩토리 메서드를 사용했습니다.
