### ISSUE TITLE
[BE] 서버/채널/카테고리/DM 카프카 이벤트 처리, 유저 메인화면/서버 Read API 구현

### ISSUE THREAD

**Issue by HanYoonSoo** [hobbytrip/hobbytrip#44]
## 작업 대상
- 유저 메인화면 Read API 
- 서버/채널/카테고리/DM 카프카 이벤트 처리
- 서버 Read API
- 유저 최근 채널 이벤트 처리

### ✅ Tasks

- [x] 서버 UD 카프카 이벤트 처리
- [x] DM U 카프카 이벤트 처리
- [x] 채널 CUD 카프카 이벤트 처리
- [x] 카테고리 CUD 카프카 이벤트 처리
- [x] 유저 메인화면 Read API 생성 및 쿼리 최적화
- [x] 서버 Read API 생성 및 쿼리 최적화
- [x] 서버 Read 시 유저 최근 채널 정보 상태관리에서 조회 
- [x] 유저 서버 생성 및 서버 참가 시 상태관리에 정보 전송

### 🙋🏻 More

서버, 유저, 서버 유저 등의 검증 작업으로 인한 쿼리 증가
 - 성능 차이는 크게 없으나 리팩토링 요망
 
유저 최근 채널 위치 저장 작업
 - 실제 서비스에서 잘 동작하는지 확인 작업
