### ISSUE TITLE
[BE] 유저 친구 CRUD 구현

### ISSUE THREAD

**Issue by ryudain05** [hobbytrip/hobbytrip#47]
## **유저 서비스 친구 API**

유저간 친구 관리를 위한 서비스

- 친구 목록 
-> 친구의 온/오프라인 확인을 위한 open feign 사용
- 친구 추가
- 친구 추가 취소  및 거절
- 친구 요청 수락

### ✅ Tasks

- [x] Dto 및 데이터베이스 생성
- [x] 친구 추가
- [x] 친구 목록
- [x] 친구 추가 취소 및 친구 삭제 
- [x] 친구 요청 수락
- [x] Exception 처리

### 🙋🏻 More

현재 임의 값으로 테스트 진행 하여서 response 값 받으면 refactor 진행할 거 같습니다.
