### ISSUE TITLE
[FE] 커뮤니티 채팅 기능 구현

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#50]
### 📄 Describe

**Stomp.js와 리액트를 사용한 커뮤니티 텍스트 채팅 채널 구현**

**⚡요구사항⚡**
- customHook과 컴포넌트를 사용하여 모듈화 하도록 한다. 
- 채팅 기록 없을 때와 있을 때 구분이 필요하다.
- 무한 스크롤 기능이 필수적이다.
- 날짜 처리를 실시간으로 가능하게 한다.
- 특정 메세지에 답장할 수 있도록 한다.
- 같은 채널에 속한 다른 사람이 채팅을 입력 중이면, 타이핑 상태를 표시해주도록 한다. 
- 메세지에 스레드를 추가적으로 생성할 수 있다.(최대 1개) 
- 파일 업로드를 할 수 있어야 한다.
- 스레드와 일반 채팅을 구분해야 한다.
- 메세지를 수정, 삭제할 수 있어야 한다. 

### ✅ Tasks

- [x] 구독 로직 정리
- [x] 채팅 조회 구현
- [x] 채팅 기록 없을 때와 있을 때 구분 
- [x] 채팅 채널 초기 화면 구현(기록 없는 경우)
- [x] 웹소켓 연결 및 구독, 발행, 채팅 전송
- [x] 무한 스크롤
- [x] 날짜 처리
- [x] 채팅 타이핑 상태 표시
- [x] 파일 업로드 기능

🕝후순위
- [x] 메세지 답장 기능
- [ ] 스레드 생성
- [x] 메세지 수정, 삭제 기능

### 🙋🏻 More

_파이팅..._

**Comment by yeahzee0421** [comment]
![image](https://github.com/hobbytrip/hobbytrip/assets/107865510/098305e8-254a-4484-9bff-9a77a9d2547d)

**Comment by yeahzee0421** [comment]
- 메세지 수정, 삭제 사항이 새로고침 없이 바로 반영되지 않는 버그 수정 
- 메세지 전송시 날짜가 NaN으로 뜨는 버그 수정
- 엔터키 눌렀을 때 메세지 전송 가능하도록 업데이트
- zustand를 사용한 웹소켓 전역 관리
