### ISSUE TITLE
[BE] FitTrip 배포 작업

### ISSUE THREAD

**Issue by HanYoonSoo** [hobbytrip/hobbytrip#75]
### 📄 Describe

FitTrip 배포를 위한 배포 진행정도 및 순서입니다.

### ✅ Tasks

- [x] API Gateway 유저 서비스 연동
- [x] API Gateway JWT 정상 검증 확인
- [x] Service Discovery 연동 확인 
- [x] OpenFeign 정상 동작 확인 
- [x] application.yml Github Submodule 작업
- [x] application.yml Jayspt 암호화 처리
- [x] Dockerfile 작성(Dockerfile 설계)
- [x] GCP 배포 서버에서 사용할 Makefile 작성
- [x] 전체 배포/무중단 배포/서비스 간 도커 네트워크를 위한 docker-compose 설계
  - [x] 로컬 가상 머신에서 무중단 배포 성공 
- [x] GCP(Google Cloud Platform) 인스턴스 구성
  - [x]  추후 성능 부족 발생시 재구성 
- [x] 도메인 구입
- [x] Nginx 설정
- [x] HTTPS 처리
- [x] 서비스 별 Spring Cloud YAML 파일 작성
- [x] Github Actions WorkFlow YAML 파일 작성
  - [x] 초안 작성 완료 
- [x] 사용한 스크립트 깃허브 업로드
