### ISSUE TITLE
상태관리서버에게 유저 입장시 유저 위치 이벤트 전송 추가

### ISSUE THREAD

**Issue by youcastle03** [hobbytrip/hobbytrip#86]
### 📄 Describe

상태관리서버에게 유저 입장시 유저 위치 이벤트 전송을 추가하고 cloud관련 설정을 했습니다.

### ✅ Tasks

- [x] Producer Config에 추가
- [x] dto 생성
- [x] 유저 입장 시  user-location-event토픽에 전송
- [x] 도커 컴포즈로 카프카 연동 테스트
