### ISSUE TITLE
[FE] 포럼 채팅 채널 구현

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#93]
### 📄 Describe

포럼 채팅 채널 구현

### ✅ Tasks

**CRUD 기반 기능** 
- [ ] 포럼 채팅 전송
- [ ] 포럼 채팅 수정
- [ ] 포럼 채팅 삭제
- [ ] 포럼 채팅 + 파일 업로드

**이벤트**
- [ ] 포럼 방 생성 
- [ ] 포럼 업데이트 이벤트
- [ ] 포럼 삭제 이벤트 

**추가 기능**
- [ ] 포럼 채팅 개수 조회
- [ ] 포럼 채팅 타이핑
- [ ] 포럼 채널 채팅 목록 조회
