### ISSUE TITLE
[FE] jwt 인증 과정 확인 

### ISSUE THREAD

**Issue by yeahzee0421** [hobbytrip/hobbytrip#98]
### 🔨 Describe
- [x] 유저 회원가입, 로그인 후 accesstoken과 refreshtoken을 로컬 스토리지에 잘 저장하는지 
- [x] `useAuthStore` token이 전역적으로 관리 잘 되는지 여부
- [x] `useUserStore` 사용자 프로필 정보 관리 잘 되는지 여부
- [x] header에 accessToken을 담아 서버에 요청이 잘 가는지 

### ✅ Tasks

.
